# Generated by Django 6.1.1 on 2026-09-21 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('apartment_number', ''), ('lodging_type', 'house'), ('room_number', '')), models.Q(('apartment_number__gt', ''), ('lodging_type', 'apartment'), ('room_number', '')), models.Q(('apartment_number__gt', ''), ('lodging_type', 'communal'), ('room_number__gt', '')), _connector='OR'), name='valid_property_lodging_type'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('living_area__lt', models.F('total_area'))), name='living_area_is_smaller_than_total_area'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.UniqueConstraint(fields=('country', 'state', 'city', 'street', 'building', 'apartment_number', 'room_number'), name='unique_property_address'),
        ),
    ]
