# Generated by Django 6.1.1 on 2026-09-23 06:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The timestamp when the object instance was originally created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='The timestamp indicating when the object was softly marked as deleted.', null=True, verbose_name='deleted at'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(help_text='The descriptive unique name of the amenity item.', max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The timestamp when the object instance was last modified.', verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(help_text='Comfort utilities provided on-site.', related_name='properties', to='properties.amenity', verbose_name='amenities'),
        ),
        migrations.AlterField(
            model_name='property',
            name='apartment_number',
            field=models.CharField(blank=True, default='', help_text='The unique apartment number inside the structure.', max_length=7, verbose_name='apartment number'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms_count',
            field=models.PositiveIntegerField(help_text='Total count of functional sanitation restrooms.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='bathrooms count'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms_count',
            field=models.PositiveIntegerField(help_text='Total count of dedicated sleeping rooms.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='bedrooms count'),
        ),
        migrations.AlterField(
            model_name='property',
            name='building',
            field=models.CharField(help_text='The building number or structure identifier.', max_length=10, verbose_name='building'),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(help_text='The city or town location.', max_length=50, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.CharField(help_text='The country where the property is located.', max_length=50, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The timestamp when the object instance was originally created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='property',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='The timestamp indicating when the object was softly marked as deleted.', null=True, verbose_name='deleted at'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Indicates if the property documents have been verified by a platform staff member.', verbose_name='is verified'),
        ),
        migrations.AlterField(
            model_name='property',
            name='kitchens_count',
            field=models.PositiveIntegerField(help_text='Total count of operational cooking areas.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='kitchens count'),
        ),
        migrations.AlterField(
            model_name='property',
            name='living_area',
            field=models.DecimalField(decimal_places=2, help_text='The net functional residential living section area measured in square units.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='living area'),
        ),
        migrations.AlterField(
            model_name='property',
            name='lodging_type',
            field=models.CharField(choices=[('house', 'Detached house'), ('apartment', 'Apartment'), ('communal', 'Communal apartment')], default='apartment', help_text='The structural category classification of the residence.', max_length=20, verbose_name='lodging type'),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(help_text='The user who owns and manages this real estate asset.', on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='property',
            name='room_number',
            field=models.CharField(blank=True, default='', help_text='The specific room identifier within a communal apartment configuration.', max_length=7, verbose_name='room number'),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(help_text='The state, region, or province of the property.', max_length=50, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='property',
            name='street',
            field=models.CharField(help_text='The street name or equivalent public address route.', max_length=50, verbose_name='street'),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_area',
            field=models.DecimalField(decimal_places=2, help_text='The gross layout area of the property measured in square units.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='total area'),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_rooms_count',
            field=models.PositiveIntegerField(help_text='Total capacity counter of all non-service rooms.', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(10)], verbose_name='total rooms count'),
        ),
        migrations.AlterField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The timestamp when the object instance was last modified.', verbose_name='updated at'),
        ),
    ]
