# Generated by Django 6.1.1 on 2026-09-23 06:45

import apps.users.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_created_at_alter_listing_deleted_at_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, default='', help_text='A short textual description or introductory notes of the profile.', max_length=200, verbose_name='biography'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='The unique primary electronic mail address used for authentication.', max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_listings',
            field=models.ManyToManyField(blank=True, help_text='Collection of bookmarked listings saved by the user.', related_name='favorited_by_users', to='listings.listing', verbose_name='favorite listings'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='The given name of the identity.', max_length=50, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='Designates whether the electronic mail identifier has been verified.', verbose_name='is email verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='', help_text='The family name of the identity.', max_length=50, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text='Enter in international format, e.g., +1234567890. Visible in listings if you are the host, and visible to both parties within a booking confirmation.', max_length=16, unique=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='An image asset reference representing the digital avatar.', null=True, upload_to=apps.users.services.user_directory_path, verbose_name='profile photo'),
        ),
    ]
