# Generated by Django 6.1.1 on 2026-09-21 14:00

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='listing title')),
                ('description', models.TextField(blank=True, default='', max_length=1000, verbose_name='listing description')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price per night')),
                ('max_guests', models.PositiveIntegerField(default=0, help_text='Maximum number of guests allowed to stay.', verbose_name='maximum guests')),
                ('min_rental_days', models.PositiveIntegerField(default=1, help_text='The minimum number of days required for a booking.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='minimum days')),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
                'db_table': 'listings',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ListingPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='listing_photos', verbose_name='photo')),
                ('photo_sequence_number', models.PositiveIntegerField(default=1, help_text='The position of the photo in the listing gallery.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='photo sequence number')),
            ],
            options={
                'verbose_name': 'Listing Photo',
                'verbose_name_plural': 'Listing Photos',
                'db_table': 'listing_photos',
                'ordering': ('photo_sequence_number',),
            },
        ),
    ]
