# Generated by Django 6.1.1 on 2026-09-21 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='property',
            field=models.OneToOneField(help_text='Property associated with the listing.', on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='properties.property', verbose_name='property'),
        ),
        migrations.AddField(
            model_name='listingphoto',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.listing', verbose_name='listing'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['title'], name='listing_title_index'),
        ),
        migrations.AddConstraint(
            model_name='listingphoto',
            constraint=models.UniqueConstraint(fields=('listing', 'photo_sequence_number'), name='unique_listing_photo_sequence_number'),
        ),
    ]
