# Generated by Django 6.1.1 on 2026-09-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this listing is visible to the public.', verbose_name='is active'),
        ),
        migrations.AddField(
            model_name='listing',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='views count'),
        ),
    ]
