# Generated by Django 6.1.1 on 2026-09-23 06:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_is_active_listing_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The timestamp when the object instance was originally created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='The timestamp indicating when the object was softly marked as deleted.', null=True, verbose_name='deleted at'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Granular description highlighting rules and benefits of the residence.', max_length=1000, verbose_name='listing description'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, help_text='The standard accommodation price for a single night stay.', max_digits=10, verbose_name='price per night'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(help_text='The public promotional title for the rental offer.', max_length=100, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='listing title'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The timestamp when the object instance was last modified.', verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='views_count',
            field=models.PositiveIntegerField(default=0, help_text='Total counter of unique details page lookups.', verbose_name='views count'),
        ),
        migrations.AlterField(
            model_name='listingphoto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The timestamp when the object instance was originally created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='listingphoto',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='The timestamp indicating when the object was softly marked as deleted.', null=True, verbose_name='deleted at'),
        ),
        migrations.AlterField(
            model_name='listingphoto',
            name='listing',
            field=models.ForeignKey(help_text='The operational rental offer this file is assigned to.', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.listing', verbose_name='listing'),
        ),
        migrations.AlterField(
            model_name='listingphoto',
            name='photo',
            field=models.ImageField(help_text='Binary image file containing the visual upload.', upload_to='listing_photos', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='listingphoto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The timestamp when the object instance was last modified.', verbose_name='updated at'),
        ),
    ]
