# Generated by Django 6.1.1 on 2026-09-21 14:00

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('check_in', models.DateField(verbose_name='check-in date')),
                ('check_out', models.DateField(verbose_name='check-out date')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('reserved', 'Reserved'), ('canceled', 'Canceled'), ('occupied', 'Occupied'), ('ended', 'Ended')], default='requested', max_length=20, verbose_name='booking status')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='total booking cost')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'bookings',
                'ordering': ('-check_in',),
            },
        ),
    ]
