# Generated by Django 6.1.1 on 2026-09-21 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('listings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='lessee',
            field=models.ForeignKey(help_text='The user who books this listing.', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='lessee'),
        ),
        migrations.AddField(
            model_name='booking',
            name='listing',
            field=models.ForeignKey(help_text='The listing this booking belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='listings.listing', verbose_name='listing'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('check_out__gt', models.F('check_in'))), name='booking_checkout_after_checkin'),
        ),
    ]
