# Generated by Django 6.1.1 on 2026-09-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='lessee_comment',
            field=models.TextField(blank=True, default='', help_text='A comment left by a potential lessee when creating a booking request.', max_length=300, verbose_name='lessee comment'),
        ),
        migrations.AddField(
            model_name='booking',
            name='lessor_comment',
            field=models.TextField(blank=True, default='', help_text='A comment left by a potential lessee when accepting or declining a booking request.', max_length=300, verbose_name='lessor comment'),
        ),
    ]
