# Generated by Django 6.1.1 on 2026-09-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_lessee_comment_booking_lessor_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The timestamp when the object instance was originally created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='The timestamp indicating when the object was softly marked as deleted.', null=True, verbose_name='deleted at'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='lessor_comment',
            field=models.TextField(blank=True, default='', help_text='A comment left by a potential lessor when accepting or declining a booking request.', max_length=300, verbose_name='lessor comment'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The timestamp when the object instance was last modified.', verbose_name='updated at'),
        ),
    ]
