# Generated by Django 6.1.1 on 2026-09-23 06:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_created_at_alter_listing_deleted_at_and_more'),
        ('reviews', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='commentator',
            field=models.ForeignKey(help_text='The authenticated user who published this review.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='commentator'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The timestamp when the object instance was originally created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='review',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='The timestamp indicating when the object was softly marked as deleted.', null=True, verbose_name='deleted at'),
        ),
        migrations.AlterField(
            model_name='review',
            name='listing',
            field=models.ForeignKey(help_text='The specific rental offer this feedback is submitted for.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='listings.listing', verbose_name='listing'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(default=5, help_text='A numerical assessment score evaluated strictly between 1 and 5 stars.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating score'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(blank=True, help_text='The written testimonial or detailed feedback content.', max_length=500, verbose_name='review text'),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The timestamp when the object instance was last modified.', verbose_name='updated at'),
        ),
    ]
